### ISSUE TITLE
path of multibyte string suport

### ISSUE THREAD

**Issue by winterxc** [oscarotero/imagecow#16]
ctype_print is not support multibyte strings.

**Comment by oscarotero** [comment]
`Image::create()` check the string and create the instance from a file path or from a binary string. But the checking is not always right ([is the best way I found to detect it](http://stackoverflow.com/questions/7146184/how-to-check-if-it-is-normal-string-or-binary-string-in-php#7146239) but not infallible, any other suggestion is welcome).

You can use `Image::createFromFile()` and `Image::createFromString()` to avoid this automatic detection and create the instance as you want.
