### ISSUE TITLE
Using this "format,jpg" returns Imagick error

### ISSUE THREAD

**Issue by eusonlito** [oscarotero/imagecow#20]
I'm using transform `format,jpg,90|resizeCrop,1840,460,center,middle` and Imagecow returns:

 ```
ErrorException in src/Libs/Imagick.php line 185:
Imagick::flattenImages method is deprecated and it's use should be avoided
```

Fixed using `$image = $image->mergeImageLayers(Imagick::LAYERMETHOD_FLATTEN);` http://php.net/manual/en/imagick.flattenimages.php#116844

**Comment by oscarotero** [comment]
Fixed in the latest release
