### ISSUE TITLE
Client Hints: example scales images with 2x too big

### ISSUE THREAD

**Issue by nodomain** [oscarotero/imagecow#26]
I tried your example under https://dev.xm1.de/client-hints/ but when using it on a retina display the image is scaled too big. See yourself ;-)
I have no clue, perhaps you have an idea.

Furthermore, your example is missing a part in this line:
$transform = isset($_GET['transform']) **? $_GET['transform']** : null;
Thanks.

**Comment by oscarotero** [comment]
Unfortunally, currently only in chrome and opera have support for client hints (http://caniuse.com/#feat=client-hints-dpr-width-viewport), other browsers display the original image.

Thanks for the example typo, it's fixed now.

**Comment by nodomain** [comment]
Of course I used Chrome to test, I forgot to add this, sorry.
When opening the page on my retina Macbook display, it is too big. When moving the Chrome window to the external non retina display, it works. Any hints?

**Comment by oscarotero** [comment]
The drp value is used to multiply the image width and height, as you can see here: https://github.com/oscarotero/imagecow/blob/master/src/Image.php#L169

It means that if you want a 200x200px image, but the drp is `2`, you get a 400x400. This is why you see different sizes in different devices.

**Comment by nodomain** [comment]
Yes but isn't it the idea of DPR that the retina representation of an image results in the same "size" on the screen but 2 pixels are used in order to display a higher resolution?
Or am I completely wrong?

**Comment by oscarotero** [comment]
As far as I know, a retina image is served at twice its desired size and then rescaled with css or width/height image attributes, because by default, the browser keeps the original size. Some articles about how use retina display images:

* http://line25.com/tutorials/how-to-create-retina-graphics-for-your-web-designs
*http://designmodo.com/responsive-retina-images/
