### ISSUE TITLE
Divide by zero when using BALANCED

### ISSUE THREAD

**Issue by everydayanchovies** [oscarotero/imagecow#40]
When x is set to BALANCED in the crop() function, given the image is square, will result in a divide by zero exception on line 93 of file Balanced.php.

**Comment by oscarotero** [comment]
I cannot reproduce this error. Can you give me an image and the code to reproduce it?
Thanks in advanced.

**Comment by everydayanchovies** [comment]
`
$imageCowPadded
                            ->crop($cropSize['width'], $cropSize['height'], Image::CROP_BALANCED)
                            ->format($image->getFileExtension())
                            ->save($croppedFilepath);
`

And any square image, I believe this one failed: https://imgur.com/fmTFIs7

cropSize width and height might be something like 300 and 500 respectively.

**Comment by everydayanchovies** [comment]
I'll do some investigating tomorrow as I don't have access to the server from home. If I can't reproduce the issue again I'll mark it as solved. Thanks for the efforts so far :)

**Comment by everydayanchovies** [comment]
I apologise, I can't reproduce the bug. It might be caused by some race condition seeing as I process many images at the same time.
Thanks again for the effort.
